apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: eroyzman/hello-gitops
  newTag: b90b02490c7d10fcd0d3d60c359acc70d267e400
